import { useEffect, useState, type FormEvent } from 'react'
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowUpRight, Plus, Heart, MessageCircle, Clock3, ArrowLeft, LogOut, PenLine, Trash2, X, Menu, Check, BookOpen } from 'lucide-react'
import { api, errorMessage } from './api'
import ThemePicker from './ThemePicker'
import { useAuth, usePosts } from './store'
import { topics, type Post, type Topic, type Kind, type Comment } from './types'

const date = (value: string) => new Date(value).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' })
const commentCount = (count: number) => `${count} ${count % 10 === 1 && count % 100 !== 11 ? 'комментарий' : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 12 || count % 100 > 14) ? 'комментария' : 'комментариев'}`
const readTime = (content: string) => Math.max(1, Math.ceil(content.trim().split(/\s+/).length / 180))
const initials = (name: string) => name.split(' ').map(x => x[0]).slice(0, 2).join('')
function Avatar({ name, small = false }: { name: string; small?: boolean }) { return <span className={`avatar ${small ? 'small' : ''}`}>{initials(name)}</span> }
function Notice({ message }: { message: string }) { return message ? <div className="notice" role="alert">{message}</div> : null }
function Loading() { return <div className="loading" role="status">Загружаем публикации<span className="dots">…</span></div> }
function PrivateRoute() { const user = useAuth(s => s.user); const location = useLocation(); return user ? <Outlet /> : <Navigate to="/login" state={{ from: location.pathname }} replace /> }

function Header() {
  const user = useAuth(s => s.user), logout = useAuth(s => s.logout)
  const [menu, setMenu] = useState(false)
  const location = useLocation(), navigate = useNavigate()
  useEffect(() => setMenu(false), [location.pathname])
  return <header className="site-header"><div className="header-inner"><Link className="brand" to="/" aria-label="Контур — главная"><span className="brand-mark">к</span>контур<span className="brand-dot">.</span></Link><nav className="main-nav"><Link className={location.pathname === '/' ? 'active' : ''} to="/">Лента</Link>{user && <Link className={location.pathname === '/mine' ? 'active' : ''} to="/mine">Мои публикации</Link>}</nav><div className="header-actions"><ThemePicker /><Link className="button primary write-button" to="/write"><Plus size={17} />Написать</Link>{user ? <><Link to="/mine" className="user-button" title={user.name}><Avatar name={user.name} small /></Link><button className="icon-button logout" title="Выйти" aria-label="Выйти" onClick={() => { logout(); navigate('/') }}><LogOut size={18} /></button></> : <Link className="login-link" to="/login">Войти</Link>}<button className="icon-button mobile-toggle" aria-label={menu ? 'Закрыть меню' : 'Открыть меню'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X size={22} /> : <Menu size={22} />}</button></div></div>{menu && <nav className="mobile-menu"><Link to="/">Лента</Link>{user && <Link to="/mine">Мои публикации</Link>}<Link to="/write">Написать публикацию</Link>{user ? <button onClick={() => { logout(); navigate('/'); setMenu(false) }}>Выйти</button> : <Link to="/login">Войти</Link>}</nav>}</header>
}
function Footer() { return <footer className="footer"><Link className="footer-brand" to="/">контур.</Link><span>Технологии. Люди. Идеи.</span><span className="footer-year">© {new Date().getFullYear()} Контур</span></footer> }
function TopicLabel({ post }: { post: Post }) { return <div className="post-tags"><span className={`topic-label ${post.topic}`}>{topics[post.topic]}</span><span className="kind-label">{post.kind === 'news' ? 'Новость' : 'Статья'}</span></div> }
function Meta({ post }: { post: Post }) { const own = useAuth(state => state.user?.id === post.authorId); return <div className="post-meta"><Avatar name={post.author.name} small /><span>{post.author.name}</span><span className="meta-separator">·</span><span>{date(post.publishedAt)}</span>{own && <span className="own-label">Ваш пост</span>}</div> }
function Stats({ post }: { post: Post }) { return <div className="post-stats"><span><Heart size={15} />{post.likesCount}</span><span><MessageCircle size={15} />{post.commentsCount}</span><span className="read-time"><Clock3 size={14} />{readTime(post.content)} мин</span></div> }
function Feature({ post }: { post: Post }) {
  const own = useAuth(state => state.user?.id === post.authorId)
  return <div className={`feature-card ${post.topic}`}><Link to={`/post/${post.id}`} className="feature-content"><div className="feature-eyebrow"><span className="feature-dot" />В ФОКУСЕ</div><TopicLabel post={post} /><h2>{post.title}</h2><p>{post.excerpt}</p><div className="feature-bottom"><Meta post={post} /><span className="round-arrow"><ArrowUpRight size={23} /></span></div></Link><div className="feature-art" aria-hidden="true"><span className="art-word">контур<span>.</span></span><div className="art-caption">ВЗГЛЯД НА ЦИФРОВОЙ МИР</div><span className="art-index">01 / ∞</span></div>{own && <Link className="feature-edit" to={`/edit/${post.id}`}><PenLine size={15} />Изменить</Link>}</div>
}

function Card({ post, mine = false, onDelete }: { post: Post; mine?: boolean; onDelete?: () => void }) { const own = useAuth(state => state.user?.id === post.authorId); return <article className={`post-card ${own ? 'own-card' : ''}`}><Link className="card-main" to={`/post/${post.id}`}><TopicLabel post={post} /><h3>{post.title}</h3><p>{post.excerpt}</p></Link><div className="card-bottom"><Meta post={post} /><Stats post={post} />{own && <div className="manage-actions"><Link to={`/edit/${post.id}`}><PenLine size={15} />Изменить</Link>{mine && <button onClick={onDelete}><Trash2 size={15} />Удалить</button>}</div>}</div></article> }
function DeleteDialog({ onClose, onConfirm, busy }: { onClose: () => void; onConfirm: () => void; busy: boolean }) {
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === 'Escape' && !busy) onClose() }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener) }, [onClose, busy])
  return <div className="modal-backdrop" onClick={() => !busy && onClose()}><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title" onClick={e => e.stopPropagation()}><h2 id="delete-title">Удалить публикацию?</h2><p>Вместе с ней будут удалены комментарии и лайки. Отменить это действие нельзя.</p><div className="dialog-actions"><button autoFocus className="button secondary" disabled={busy} onClick={onClose}>Отмена</button><button className="button danger" disabled={busy} onClick={onConfirm}>{busy ? 'Удаляем…' : 'Удалить'}</button></div></div></div>
}
function Feed({ mine = false }: { mine?: boolean }) {
  const { posts, popular, loading, error, load, remove } = usePosts()
  const user = useAuth(s => s.user)
  const [params, setParams] = useSearchParams()
  const topic = params.get('topic') as Topic | null, kind = params.get('kind') as Kind | null
  const [deleting, setDeleting] = useState<Post | null>(null), [busy, setBusy] = useState(false), [actionError, setActionError] = useState('')
  useEffect(() => { void load({ ...(topic && topic in topics ? { topic } : {}), ...(kind === 'news' || kind === 'article' ? { kind } : {}) }, mine) }, [topic, kind, mine, user?.id, load])
  const filter = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next) }
  const confirmDelete = async () => { if (!deleting) return; setBusy(true); try { await remove(deleting.id); setDeleting(null) } catch (e) { setActionError(errorMessage(e)); setDeleting(null) } finally { setBusy(false) } }
  const feature = !mine && !topic && !kind && posts[0], cards = feature ? posts.slice(1) : posts
  return <main className="page feed-page"><section className="feed-heading"><div><div className="eyebrow">{mine ? 'КАБИНЕТ АВТОРА' : 'НЕЗАВИСИМОЕ ЦИФРОВОЕ МЕДИА'}</div><h1>{mine ? 'Мои публикации' : <>Всё интересное.<br /><span>В одном контуре.</span></>}</h1><p>{mine ? `${user?.name}, здесь ваши истории и идеи.` : 'Технологии, игры, дизайн и жизнь в интернете. Читаем, делимся, обсуждаем.'}</p></div><div className="heading-note"><BookOpen size={22} /><span>{mine ? 'Каждая история начинается с идеи.' : 'Свежий взгляд на привычные вещи.'}</span></div></section>{!mine && <section className="filter-bar" aria-label="Фильтры публикаций"><div className="topic-filters"><button className={!topic ? 'selected' : ''} onClick={() => filter('topic', '')}>Все темы</button>{Object.entries(topics).map(([key, label]) => <button key={key} className={topic === key ? 'selected' : ''} onClick={() => filter('topic', key)}>{label}</button>)}</div><label className="kind-select"><span className="sr-only">Вид публикации</span><select value={kind || ''} onChange={e => filter('kind', e.target.value)}><option value="">Все публикации</option><option value="article">Статьи</option><option value="news">Новости</option></select></label></section>}<Notice message={error || actionError} />{loading ? <Loading /> : error ? <button className="button secondary" onClick={() => void load({ ...(topic && topic in topics ? { topic } : {}), ...(kind === 'news' || kind === 'article' ? { kind } : {}) }, mine)}>Повторить загрузку</button> : <>{feature && <Feature post={feature} />}{!mine && !topic && !kind && popular.length > 0 && <section className="popular-section"><div className="section-heading"><h2><Heart size={19} />Больше всего лайков</h2></div><p className="popular-description">Публикации, которые понравились читателям. Возможно, понравятся и вам.</p><div className="post-grid">{popular.map(post => <Card key={post.id} post={post} />)}</div></section>}<div className="section-heading"><h2>{mine ? 'Ваши материалы' : topic && topic in topics ? topics[topic] : 'Последние публикации'}<span>{cards.length}</span></h2>{mine ? <Link to="/write" className="text-link"><Plus size={16} />Новая публикация</Link> : <span>Сначала новые</span>}</div>{cards.length ? <div className="post-grid">{cards.map(post => <Card key={post.id} post={post} mine={mine} onDelete={() => { setActionError(''); setDeleting(post) }} />)}</div> : <div className="empty"><BookOpen size={32} /><h3>{mine ? 'Пока нет публикаций' : 'Здесь пока тихо'}</h3><p>{mine ? 'Поделитесь первой историей — она появится в общей ленте.' : 'Попробуйте выбрать другую тему или вид публикации.'}</p>{mine && <Link className="button primary" to="/write">Написать статью</Link>}</div>}</>}{deleting && <DeleteDialog onClose={() => setDeleting(null)} onConfirm={() => void confirmDelete()} busy={busy} />}</main>
}
function AuthPage({ register = false }: { register?: boolean }) {
  const login = useAuth(s => s.login), signUp = useAuth(s => s.register), user = useAuth(s => s.user)
  const [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const navigate = useNavigate(), location = useLocation()
  const destination = typeof location.state?.from === 'string' && location.state.from.startsWith('/') && !location.state.from.startsWith('//') ? location.state.from : '/'
  if (user) return <Navigate to={destination} replace />
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { if (register) await signUp(String(form.get('name')), String(form.get('email')), String(form.get('password'))); else await login(String(form.get('email')), String(form.get('password'))); navigate(destination, { replace: true }) } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
  return <main className="auth-page"><div className="auth-intro"><div className="eyebrow">ВАШ ГОЛОС ИМЕЕТ ЗНАЧЕНИЕ</div><h1>Хорошие идеи<br />заслуживают<br /><span>разговора.</span></h1><p>Публикуйте истории, находите новые взгляды и обсуждайте то, что вам интересно.</p><div className="auth-decoration">к<span>.</span></div></div><section className="auth-form-wrap" key={register ? 'register' : 'login'}><Link className="back-link" to="/"><ArrowLeft size={16} />В ленту</Link><h2>{register ? 'Присоединиться' : 'С возвращением'}</h2><p>{register ? 'Создайте аккаунт в Контуре' : 'Войдите, чтобы продолжить разговор'}</p><form onSubmit={submit}>{register && <label>Ваше имя<input name="name" autoComplete="name" required minLength={2} maxLength={60} placeholder="Как к вам обращаться" /></label>}<label>Email<input name="email" type="email" autoComplete="email" required maxLength={150} placeholder="you@example.com" /></label><label>Пароль<input name="password" type="password" autoComplete={register ? 'new-password' : 'current-password'} required minLength={register ? 8 : 1} maxLength={72} placeholder={register ? 'Не менее 8 символов' : 'Ваш пароль'} /></label><Notice message={error} /><button className="button primary auth-submit" disabled={busy}>{busy ? 'Подождите…' : register ? 'Создать аккаунт' : 'Войти'}</button></form><div className="auth-switch">{register ? 'Уже есть аккаунт?' : 'Ещё нет аккаунта?'} <Link state={location.state} to={register ? '/login' : '/register'}>{register ? 'Войти' : 'Зарегистрироваться'}</Link></div></section></main>
}
function PostPage() {
  const { id } = useParams(), user = useAuth(s => s.user)
  const [post, setPost] = useState<Post | null>(null), [comments, setComments] = useState<Comment[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [actionError, setActionError] = useState(''), [busy, setBusy] = useState(false), [likeBusy, setLikeBusy] = useState(false), [text, setText] = useState('')
  const navigate = useNavigate()
  useEffect(() => { let active = true; setLoading(true); setError(''); setActionError(''); setText(''); Promise.all([api.get(`/posts/${id}`), api.get(`/posts/${id}/comments`)]).then(([p, c]) => { if (active) { setPost(p.data); setComments(c.data) } }).catch(e => { if (active) setError(errorMessage(e)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [id, user?.id])
  const like = async () => { if (!user) { navigate('/login', { state: { from: `/post/${id}` } }); return } if (!post || likeBusy) return; setLikeBusy(true); setActionError(''); try { const { data } = post.liked ? await api.delete(`/posts/${id}/like`) : await api.put(`/posts/${id}/like`); setPost({ ...post, ...data }) } catch(e) { setActionError(errorMessage(e)) } finally { setLikeBusy(false) } }
  const send = async (event: FormEvent) => { event.preventDefault(); if (!post) return; setBusy(true); setActionError(''); try { const { data } = await api.post(`/posts/${id}/comments`, { text }); setComments(prev => [...prev, data]); setPost({ ...post, commentsCount: post.commentsCount + 1 }); setText('') } catch(e) { setActionError(errorMessage(e)) } finally { setBusy(false) } }
  const deleteComment = async (commentId: string) => { if (busy) return; setBusy(true); try { await api.delete(`/comments/${commentId}`); setComments(prev => prev.filter(x => x.id !== commentId)); setPost(prev => prev ? { ...prev, commentsCount: prev.commentsCount - 1 } : prev) } catch(e) { setActionError(errorMessage(e)) } finally { setBusy(false) } }
  if (loading) return <main className="page"><Loading /></main>
  if (error || !post) return <main className="page"><Notice message={error || 'Публикация не найдена'} /><Link className="button secondary" to="/">Вернуться в ленту</Link></main>
  return <main className="article-page"><Link className="back-link" to="/"><ArrowLeft size={16} />Все публикации</Link><article><TopicLabel post={post} /><h1>{post.title}</h1><p className="article-excerpt">{post.excerpt}</p><div className="article-author"><Avatar name={post.author.name} /><div><strong>{post.author.name}</strong><span>{date(post.publishedAt)} · {readTime(post.content)} мин чтения</span></div>{user?.id === post.authorId && <Link className="edit-link" to={`/edit/${post.id}`}><PenLine size={17} />Редактировать</Link>}</div><div className="article-body">{post.content.split(/\n\s*\n/).map((paragraph, i) => <p key={i}>{paragraph}</p>)}</div><div className="article-reactions"><button aria-label={post.liked ? 'Убрать лайк' : 'Поставить лайк'} aria-pressed={post.liked} disabled={likeBusy} className={`like-button ${post.liked ? 'liked' : ''}`} onClick={() => void like()}><Heart size={20} fill={post.liked ? 'currentColor' : 'none'} />{post.likesCount}<span>{post.liked ? 'Вам нравится' : 'Нравится'}</span></button><span><MessageCircle size={18} />{commentCount(comments.length)}</span></div></article><section className="comments-section"><h2>Обсуждение<span>{comments.length}</span></h2><Notice message={actionError} />{user ? <form className="comment-form" onSubmit={send}><label htmlFor="comment">Поделитесь своим мнением</label><textarea id="comment" value={text} onChange={e => setText(e.target.value)} required maxLength={2000} placeholder="Что вы думаете об этом?" rows={3} /><button className="button primary" disabled={busy || !text.trim()}>{busy ? 'Подождите…' : 'Отправить комментарий'}</button></form> : <div className="comment-invite">Присоединяйтесь к разговору. <Link to="/login" state={{ from: `/post/${id}` }}>Войдите</Link>, чтобы оставить комментарий.</div>}<div className="comments-list">{comments.map(comment => <article className="comment" key={comment.id}><Avatar name={comment.author.name} /><div className="comment-content"><div className="comment-meta"><strong>{comment.author.name}</strong><span>{date(comment.createdAt)}</span>{user?.id === comment.author.id && <button className="icon-button" title="Удалить комментарий" aria-label="Удалить свой комментарий" disabled={busy} onClick={() => void deleteComment(comment.id)}><Trash2 size={15} /></button>}</div><p>{comment.text}</p></div></article>)}{!comments.length && <p className="muted">Обсуждение ещё не началось. Ваш комментарий может стать первым.</p>}</div></section></main>
}
function Editor() {
  const { id } = useParams(), navigate = useNavigate(), user = useAuth(s => s.user), save = usePosts(s => s.save)
  const [title, setTitle] = useState(''), [excerpt, setExcerpt] = useState(''), [content, setContent] = useState(''), [topic, setTopic] = useState<Topic>('technology'), [kind, setKind] = useState<Kind>('article'), [busy, setBusy] = useState(false), [loading, setLoading] = useState(!!id), [error, setError] = useState(''), [loadFailed, setLoadFailed] = useState(false)
  useEffect(() => { if (!id) return; let active = true; api.get(`/posts/${id}`).then(({ data }) => { if (!active) return; if (data.authorId !== user?.id) { setError('Можно редактировать только свои публикации'); setLoadFailed(true); return } setTitle(data.title); setExcerpt(data.excerpt); setContent(data.content); setTopic(data.topic); setKind(data.kind) }).catch(e => { if (active) { setError(errorMessage(e)); setLoadFailed(true) } }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [id, user?.id])
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const post = await save({ title, excerpt, content, topic, kind }, id); navigate(`/post/${post.id}`) } catch(e) { setError(errorMessage(e)) } finally { setBusy(false) } }
  if (loading) return <main className="page"><Loading /></main>
  return <main className="editor-page"><Link to="/mine" className="back-link"><ArrowLeft size={16} />Мои публикации</Link><div className="eyebrow">КАБИНЕТ АВТОРА</div><h1>{id ? 'Редактировать публикацию' : 'Ваша новая история'}</h1><p className="muted">Начните с идеи. Оформление мы берём на себя.</p><Notice message={error} />{!loadFailed && <form className="editor-form" onSubmit={submit}><div className="form-row"><label>Вид публикации<select value={kind} onChange={e => setKind(e.target.value as Kind)}><option value="article">Статья</option><option value="news">Новость</option></select></label><label>Тема<select value={topic} onChange={e => setTopic(e.target.value as Topic)}>{Object.entries(topics).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><label>Заголовок<input value={title} onChange={e => setTitle(e.target.value)} required minLength={3} maxLength={150} placeholder="О чём ваша публикация?" /></label><label>Короткое описание <span className="optional">необязательно</span><textarea value={excerpt} onChange={e => setExcerpt(e.target.value)} maxLength={280} rows={2} placeholder="Пара предложений для карточки в ленте" /></label><label>Текст<textarea className="content-input" value={content} onChange={e => setContent(e.target.value)} required minLength={20} maxLength={30000} rows={13} placeholder="Расскажите свою историю. Разделяйте абзацы пустой строкой." /></label><div className="editor-bottom"><span>{content.length.toLocaleString('ru-RU')} / 30 000 символов</span><button disabled={busy} className="button primary"><Check size={17} />{busy ? 'Сохраняем…' : id ? 'Сохранить изменения' : 'Опубликовать'}</button></div></form>}</main>
}
function NotFound() { return <main className="page empty"><div className="eyebrow">404</div><h1>Страница потерялась</h1><p>Вернёмся туда, где есть что почитать.</p><Link to="/" className="button primary">В ленту</Link></main> }
function ScrollTop() { const { pathname } = useLocation(); useEffect(() => { window.scrollTo(0, 0) }, [pathname]); return null }
export default function App() {
  const ready = useAuth(s => s.ready), initialize = useAuth(s => s.initialize), logout = useAuth(s => s.logout)
  useEffect(() => { void initialize(); window.addEventListener('kontur:logout', logout); return () => window.removeEventListener('kontur:logout', logout) }, [initialize, logout])
  return <><ScrollTop /><Header />{!ready ? <main className="page"><Loading /></main> : <Routes><Route path="/" element={<Feed />} /><Route path="/post/:id" element={<PostPage />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route element={<PrivateRoute />}><Route path="/mine" element={<Feed mine />} /><Route path="/write" element={<Editor key="new" />} /><Route path="/edit/:id" element={<Editor />} /></Route><Route path="*" element={<NotFound />} /></Routes>}<Footer /></>
}
